config:
  target: "http://localhost:3000"
  phases:
    - duration: 10
      arrivalRate: 10
      name: Warm up
    - duration: 200
      arrivalRate: 10
      rampTo: 100
      name: Ramp up load
    - duration: 100
      arrivalRate: 500
      name: Sustained load
  # payload:
  #   # Load search keywords from an external CSV file and make them available
  #   # to virtual user scenarios as variable "keywords":
  #   path: "keywords.csv"
  #   fields:
  #     - "keywords"
scenarios:
  # We define one scenario:
  - name: "Home page"
    flow:
      # - post:
      #     url: "/"
      #     # body: "kw={{ keywords }}"
      #     # The endpoint responds with JSON, which we parse and extract a field from
      #     # to use in the next request:
      #     # capture:
      #     # json: "$.results[0].id"
      #     # as: "id"
      # # Get the details of the product:
      # - get:
      #     url: "/product/{{ id }}/details"
      # Pause for 3 seconds:
      # - think: 3
      # Add product to cart:
      # - post:
      #     url: "/cart"
      #     json:
      #       productId: "{{ id }}"
      - get:
          url: "/"
